# Generated by Django 4.1.4 on 2024-09-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_register', '0002_remove_transaccion_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='descripcion',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
