# Generated by Django 4.1.4 on 2024-09-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_register', '0003_transaccion_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='id',
            field=models.CharField(editable=False, max_length=12, primary_key=True, serialize=False),
        ),
    ]
