# Generated by Django 4.1.4 on 2024-10-16 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_register', '0003_caja_total_entradas_caja_total_salidas'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='diferencia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='caja',
            name='valor_esperado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
