# Generated by Django 4.1.4 on 2023-11-07 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleproduct',
            old_name='product',
            new_name='code',
        ),
    ]
