# Generated by Django 4.1.4 on 2024-09-08 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='caja',
        ),
    ]
