# Generated by Django 4.1.4 on 2023-11-07 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0002_rename_product_saleproduct_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='change',
            field=models.DecimalField(decimal_places=2, default=11, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='pay',
            field=models.DecimalField(decimal_places=2, default=123, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='full_value',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
