# Generated by Django 4.1.4 on 2023-11-07 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0003_sales_change_sales_pay_alter_saleproduct_full_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='change',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
