# Generated by Django 4.1.4 on 2024-01-01 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0005_alter_sales_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='pay',
            field=models.DecimalField(decimal_places=2, max_digits=99),
        ),
    ]
