# Generated by Django 4.1.4 on 2024-01-01 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0006_alter_sales_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='change',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=99),
        ),
        migrations.AlterField(
            model_name='sales',
            name='valor_final',
            field=models.DecimalField(decimal_places=2, max_digits=99),
        ),
    ]
