# Generated by Django 4.1.4 on 2024-01-08 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics_products',
            name='revenue',
            field=models.DecimalField(decimal_places=0, max_digits=99),
        ),
        migrations.AlterField(
            model_name='statistics_products',
            name='sold_value',
            field=models.DecimalField(decimal_places=0, max_digits=99),
        ),
    ]
