# Generated by Django 4.1.4 on 2023-11-07 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='id',
        ),
        migrations.AlterField(
            model_name='products',
            name='code',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
